version: '3.8'
services:
  db:
    container_name: db
    build:
      context: ./db/srcs
    expose:
      - "5432"
    networks:
      - trans-network

networks:
  trans-network:
    driver: bridge
